name: Generate Audio Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install gtts

      - name: Generate audio files
        run: python generate_audio.py

      - name: Upload audio.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: audio-files
          path: audio.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: audio.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
